function mexbuild

%% Change these to the appropriate paths on your system
eigen3_path = '/opt/homebrew/include/eigen3';
gmp_path = '/opt/homebrew';
suitesparse_path =  '/opt/homebrew';
directional_path = '../../../external/Directional/';
libigl_v2_4_path = '../../../external/libigl/';
geomcentral_include_path = '../../../external/geometry-central/include';
geomcentral_lib_path = '../../../external/geometry-central/build/src';

%% Build MEX files
directional_mex_files = {'quad_mesh_directional_mex.cpp', 'compute_field_directional_mex.cpp'};
for j = 1:length(directional_mex_files)
    mex(['-I' fullfile(gmp_path, 'include')], ...
        ['-I' eigen3_path], ...
        ['-I' fullfile(libigl_v2_4_path, 'include')], ...
        ['-I' fullfile(directional_path, 'include')], ...
        ['-I' fullfile(directional_path, 'external/SaddlePoint/include')], ...
        ['-L' fullfile(gmp_path, 'lib')], ...
        '-lgmp', ...
        '-O', directional_mex_files{j});
end

mex(['-I' geomcentral_include_path], ...
    ['-I' fullfile(suitesparse_path, 'include')], ...
    ['-I' eigen3_path], ...
    ['-L' fullfile(suitesparse_path, 'lib')], ...
    ['-L' geomcentral_lib_path], ...
    '-lgeometry-central', ...
    '-lcholmod', ...
    '-lumfpack', ...
    '-O', 'compute_field_geometry_central_mex.cpp');

end